export const catalogo = [
    {
        id:1,
        imagen:"./assets/products/SNKMASTER.webp",
        nombre:"SNK MASTER",
        precio:1700000,
        descripcion:"Ryzen 7 8700X, RTX 3080, 32GB RAM 3200MHZ ...",
        categoria:"pc-armada",
    },
    {
        id:2,
        imagen:"./assets/products/SNKPRIME.webp",
        nombre:"SNK PRIME",
        precio:1200000,
        descripcion:"I7 15700F, RTX 3060TI, 32GB RAM 3200MHZ ...",
        categoria:"pc-armada",
    },
    {
        id:3,
        imagen:"./assets/products/SNKBEGIN.webp",
        nombre:"SNK BEGIN",
        precio:850000,
        descripcion:"Ryzen 5 3600X, RTX 2060, 16GB RAM 3200MHZ ...",
        categoria:"pc-armada",
    },
    {
        id:4,
        imagen:"./assets/products/2070TI.webp",
        nombre:"RTX 2070TI",
        precio:355000,
        descripcion:"Velocidad Reloj: 1770MHz Memoria: 8 GB GDDR6",
        categoria:"gpu",
    },
    {
        id:5,
        imagen:"./assets/products/4080.webp",
        nombre:"RTX 4080",
        precio:1100000,
        descripcion:"Velocidad Reloj: 2510MHz Memoria: 16 GB GDDR6X",
        categoria:"gpu",
    },
    {
        id:6,
        imagen:"./assets/products/2060SUPER.webp",
        nombre:"RTX 2060S",
        precio:250000,
        descripcion:"Velocidad Reloj: 1470MHz Memoria: 8GB GDDR6",
        categoria:"gpu",
    },
    {
        id:7,
        imagen:"./assets/products/HDD1TB.webp",
        nombre:"WD BLUE 1TB",
        precio:80000,
        descripcion:"Transferencia de Datos: 185MB/s 7200RPM",
        categoria:"hdd",
    },
    {
        id:8,
        imagen:"./assets/products/HDD2TB.webp",
        nombre:"WD BLUE 2TB",
        precio:165000,
        descripcion:"Transferencia de Datos: 240MB/s 7200RPM",
        categoria:"hdd",
    },
    {
        id:9,
        imagen:"./assets/products/HDD6TB.webp",
        nombre:"SEAGATE 6TB",
        precio:350000,
        descripcion:"Transferencia de Datos: 300MB/s 7200RPM",
        categoria:"hdd",
    },
    {
        id:10,
        imagen:"./assets/products/GSKILL-16gb.webp",
        nombre:"G.SKILL 16GB",
        precio:42000,
        descripcion:"RGB DDR4 3200MHZ CL16.16.16",
        categoria:"ram",
    },
    {
        id:11,
        imagen:"./assets/products/HyperX2x8.webp",
        nombre:"HYPERX 2X8GB",
        precio:77000,
        descripcion:"2X8 RGB DDR4 3200MHZ CL16.16.16",
        categoria:"ram",
    },
    {
        id:12,
        imagen:"./assets/products/KINGSTON8GB.webp",
        nombre:"KINGSTON 8GB",
        precio:75000,
        descripcion:"RGB DDR5 4500MHZ CL 17.16.17",
        categoria:"ram",
    },
    {
        id:13,
        imagen:"./assets/products/AIRBLADER.webp",
        nombre:"AIRBLADER",
        precio:34000,
        descripcion:"16000dpi 2000HZ, 2 BOTONES LATERALES",
        categoria:"mouse",
    },
    {
        id:14,
        imagen:"./assets/products/DEATHADDER.webp",
        nombre:"DEATHADDER",
        precio:120000,
        descripcion:"18000dpi 1000HZ, 2 BOTONES LATERALES",
        categoria:"mouse",
    },
    {
        id:15,
        imagen:"./assets/products/LOGITECH-G309.webp",
        nombre:"G309",
        precio:165000,
        descripcion:"WIRELESS 16000dpi 1000MHZ",
        categoria:"mouse",
    },
    {
        id:16,
        imagen:"./assets/products/ASUSMONITOR.webp",
        nombre:"ASUS DISPLAY",
        precio:275000,
        descripcion:"1920x1080 135hz 16:9 OLED GLASS",
        categoria:"monitores",
    },
    {
        id:17,
        imagen:"./assets/products/LGMONITOR.webp",
        nombre:"LG DISPLAY",
        precio:192000,
        descripcion:"1920x1080 175hz 16:9 OLED GLASS",
        categoria:"monitores",
    },
    {
        id:18,
        imagen:"./assets/products/GIGABYTEMONITOR.webp",
        nombre:"GB MONITOR",
        precio:125000,
        descripcion:"1600x900 144hz 4:3 OLED GLASS",
        categoria:"monitores",
    },
]